// <auto-generated />
using EF_2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_2.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250313114726_Migration01")]
    partial class Migration01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_2.Models.Student", b =>
                {
                    b.Property<int>("St_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("St_Id"));

                    b.Property<int>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<string>("St_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("St_Age")
                        .HasColumnType("int");

                    b.Property<string>("St_FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("St_LName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("St_Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
