// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF_3.Models;

[Index("au_lname", "au_fname", Name = "aunmind")]
public partial class author
{
    [Key]
    [StringLength(11)]
    [Unicode(false)]
    public string au_id { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string au_lname { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string au_fname { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string phone { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string address { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string city { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string state { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string zip { get; set; }

    public bool? contract { get; set; }

    [InverseProperty("au")]
    public virtual ICollection<titleauthor> titleauthors { get; set; } = new List<titleauthor>();

    public override string ToString()
    {
        return $"{au_fname}\t|{au_id}";
    }
}