// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF_3.Models;

[PrimaryKey("au_id", "title_id")]
[Table("titleauthor")]
[Index("au_id", Name = "auidind")]
[Index("title_id", Name = "titleidind")]
public partial class titleauthor
{
    [Key]
    [StringLength(11)]
    [Unicode(false)]
    public string au_id { get; set; }

    [Key]
    [StringLength(6)]
    [Unicode(false)]
    public string title_id { get; set; }

    public byte? au_ord { get; set; }

    public int? royaltyper { get; set; }

    [ForeignKey("au_id")]
    [InverseProperty("titleauthors")]
    public virtual author au { get; set; }

    [ForeignKey("title_id")]
    [InverseProperty("titleauthors")]
    public virtual title title { get; set; }
}